### ISSUE TITLE
grype scan is failing with following 

### ISSUE THREAD

**Issue by kevinpatel27** [anchore/circleci-orb-grype#2]
**What happened**:

```sh
#!/bin/sh -eo pipefail
# Error calling workflow: 'build_test'
# Error calling job: 'list-container-vulnerabilities'
# Cannot find a definition for command named grype/list-image-vulns
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by jonasagx** [comment]
Hi @kevinpatel27 I am not sure this is a problem with this orb or with your configuration. A quick google search showed other users facing [similar problems because of misconfiguration](https://discuss.circleci.com/t/orbs-cannot-find-a-definition-for-command-named/34530).

The best way to understand what is happening is via reproducible steps, a snippet of how you're using this orb would be great.

**Comment by kevinpatel27** [comment]
Thanks for the reply. I am new to circle ci and trying this orb as this is a requirement for my project. However now i am seeing another exception:

#!/bin/bash -eo pipefail
. src/scripts/scan-image.sh && ScanImage
/bin/bash: src/scripts/scan-image.sh: No such file or directory

Exited with code exit status 1
CircleCI received exit code 1

Do we need to copy the source directory to config file root directory in order for this to work?

**Comment by hsoerensen** [comment]
I'm looking into this as well, as I'm getting the same error as referenced just above ('No such file or directory`), and it appears to me that the source code from the `src/scripts` folder are missing from the packaged orb.

When doing `circleci orb source anchore/grype` (to get the source) the scripts are not embedded. Loosely thinking that they should be included via usage of `<<include(file)>>`

**Comment by jonasagx** [comment]
Thank you for the info. I've found the problem in this orb's release process, and have a PR to address it: https://github.com/anchore/circleci-orb-grype/pull/4 I deployed it to `dev:alpha`. 
You can check it with `circleci orb source anchore/grype@dev:alpha`, it should fix the issue where scripts can't be located. Once I adjust integration tests failures I will release it as the latest version.

FYI: you can import `anchore/grype@dev:alpha` and test your use-cases. Please let me know if other issues appear.

**Comment by jonasagx** [comment]
This ticket was closed because the fixing PR was merged, if you still experience problems we can reopen this ticket and discuss further. I've cut a new version and it should be released today.
